# Generated by Django 5.0.1 on 2024-02-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_basicbuildingdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicbuildingdetails',
            name='user',
        ),
    ]
